dataset:
  name: scannet
  num_views: 12
  image_dir: data/scannet/test
  resolution_h: 192
  resolution_w: 256
  data_load_mode: two_stage
  test_interval: -1
  gen_data_ratio: 1.0
train:
  lr: 0.0002

model:
  model_id: stabilityai/stable-diffusion-2-depth
  depth_config: configs/depth_preprocessor_config.json
  guidance_scale: 9.
  diff_timestep: 50
  model_type: depth
  overlap_filter: 0.3
  unet_train: False
    
